version: '3.8'
services:

 backend:
  build: './server'
  image: 'backend'
  container_name: compressor-backend
  ports:
  - "3000:3000"
 
 frontend:
  build: './client'
  image: 'frontend'
  container_name: 'compressor-frontend'  
  ports:
  - "5173:5173"